export default [
  { path: '/user', layout: false, routes: [{ path: '/user/login', component: './User/Login' }] },
  { path: '/user', layout: false, routes: [{ path: '/user/registry', component: './User/Registry' }] },
  { path: '/', redirect: '/book/buy' },
  { path: '/user/management', name: '用户管理', icon: 'pieChart', component: './User/Management' },
  { path: '/user/update', name: '用户更新', icon: 'pieChart', component: './User/Update'},
  { path: '/user/profile', name: '个人信息', icon: 'pieChart', component: './User/Profile' },
  { path: '/book/management', name: '书籍管理', icon: 'pieChart', component: './Book/Management' },
  { path: '/book/add', name: '添加书籍', icon: 'barChart', component: './Book/Add' },
  { path: '/book/info', name: '书籍详细信息', icon: 'pieChart', component: './Book/Info', menu: false },
  { path: '/book/detail', name: '书籍详细信息', icon: 'pieChart', component: './Book/Detail', menu: false },
  { path: '/book/update', name: '更新书籍', icon: 'pieChart', component: './Book/Update' },
  { path: '/book/buy', name: '购买书籍', icon: 'pieChart', component: './Book/Buy' },
  { path: '/book/Borrow', name: '借阅书籍', icon: 'pieChart', component: './Book/Borrow' },
  { path: '/bank/profile', name: '账户信息', icon: 'pieChart', component: './Bank/Profile' },
  { path: '/bank/recharge', name: '账户充值', icon: 'pieChart', component: './Bank/Recharge' },
  // {
  //   path: '/admin',
  //   icon: 'crown',
  //   access: 'canAdmin',
  //   routes: [
  //     { path: '/admin', name: '管理页面', redirect: '/admin/sub-page' },
  //     { path: '/admin/sub-page', name: '管理页面2', component: './Admin' },
  //   ],
  // },
  { path: '/', redirect: '/welcome' },
  { path: '*', layout: false, component: './404' },
];
